### ISSUE TITLE
first issue

### ISSUE THREAD

**Issue by Jesande** [Jesande/jesande.github.io#1]
##@gorazd 
Would you please help decide which version is better?
Separated pages like this:
 https://xd.adobe.com/view/4bd8b120-8465-4bb6-7635-940393c998d3-3de9/
Or one page like this:
  https://xd.adobe.com/view/386ebd2e-d969-427d-6bf1-31906411a54d-4e5f/

**Comment by gorazd** [comment]
I think both are valid solutions. What will be easier for you to implement/maintain?

Let's say you you to send a link to your **About** section, 
if you make separate pages ...com/about
if you have the sections in one page ...com#about

**Comment by Jesande** [comment]
I'm going to keep the scroll,
So it would be 4 sections, is it ok if I use a <main> as a grid wrapper with 4 rows(one for each section)?

**Comment by gorazd** [comment]
You can also simply use a wrapper and four sections.
As they are block-level elements they will be distributed one below the other.

**Comment by Jesande** [comment]
ok, good
I just pushed my first try for the HTML and CSS.
There are many mistakes in spacing but I'll keep working on it.
Please check if it's ok in the general terms!
Thank you!!

**Comment by gorazd** [comment]
Looks good! Keep working and updating me.

Try adding the `scroll-behavior` property to the <html> element, you should see smooth scrolling between the sections (in the browsers that support it).
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior

**Comment by Jesande** [comment]
I applied, thank you!
