### ISSUE TITLE
dots navigation

### ISSUE THREAD

**Issue by Jesande** [Jesande/jesande.github.io#11]
why the first dot is always active?

**Comment by gorazd** [comment]
https://www.dropbox.com/s/9a3lq7d8j0m7zw5/Screenshot%202020-05-14%2012.42.58.png?dl=0

**Comment by Jesande** [comment]
```
nav#dot-nav a.active, nav#dot-nav a:first-child {
nav#dot-nav a.active {
  background: var(--black);
}
```
if I delete the first child then every dot goes black, but its ok, i got it now.

**Comment by Jesande** [comment]
that's the problem to copy and paste without knowing hehe
I'm gonna try to fix the scroll reveal...

**Comment by Jesande** [comment]
If I navigate clicking in the dots, the section changes with a nice scroll.
I tried to apply that to the main menu using this 
(https://www.cssscript.com/easy-one-page-scroll-navigation-library-slide-nav/)
but I couldn't get it to work.

**Comment by gorazd** [comment]
```
nav#dot-nav a.active, nav#dot-nav a:first-child {
nav#dot-nav a.active {
  background: var(--black);
}
```
should be 
```
nav#dot-nav a.active {
  background: var(--black);
}
```

**Comment by gorazd** [comment]
For the smooth navigation use
`scroll-behavior: smooth;`
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior
https://css-tricks.com/almanac/properties/s/scroll-behavior/
