### ISSUE TITLE
Nav

### ISSUE THREAD

**Issue by Jesande** [Jesande/jesande.github.io#3]
How can I change the text color depending on the section in which it is over?
white if it is over purple.
grey if it is over white.

**Comment by gorazd** [comment]
The `mix-blend-mode` works on the parents background color.

If you move the header into section.home it should work.

**Comment by Jesande** [comment]
right now it has` mix-blend-mode` but it is
dark purple(not white) if it is over purple.
grey if it is over white.

**Comment by gorazd** [comment]
I was looking for a solution, there is no easy way.
We can implement this later using JavaScript.
