### ISSUE TITLE
trypewrite animation

### ISSUE THREAD

**Issue by Jesande** [Jesande/jesande.github.io#5]
can you help me fix this? 
https://github.com/Jesande/jesande.github.io/blob/7681dbce463f80b35c4a8adc4ef4049d8bb3e2f2/style.css#L112-L130

how can I make it a loop? and the spaces are not matching with the letters..

**Comment by gorazd** [comment]
To make an animation loop use:
`animation-iteration-count: infinite;`

You might want to use a monospace font for this text, where each letter is of the same width. Like on a typewriter :)

Mono spaced
https://fonts.google.com/specimen/IBM+Plex+Mono
https://fonts.google.com/specimen/Roboto+Mono
https://www.recursive.design/
https://fonts.google.com/specimen/Space+Mono

**Comment by Jesande** [comment]
ok, it's a loop now, but my idea was that the word changes.. like write "ciao" and delete it, then write "hello" and delete it...
Anyway, I'm gonna postpone that.

**Comment by gorazd** [comment]
You can use a CSS only solution:
https://css-tricks.com/snippets/css/typewriter-effect/
Oh, you already used this :) if you want the word to change you could apply a delay to the second word animation.

There are also some JS libraries like:
https://github.com/tameemsafi/typewriterjs
you need to link the dist/core.js file in your HTML
