### ISSUE TITLE
New branch

### ISSUE THREAD

**Issue by Jesande** [Jesande/jesande.github.io#6]
I created a new branch to try another layout, and now I want to make it the master branch or be able to see it in https://jesande.github.io/

**Comment by gorazd** [comment]
You can merge it into your master branch.

Check out Netlify's option to preview various branches:
https://www.netlify.com/blog/2017/11/16/get-full-control-over-your-deployed-branches/

**Comment by Jesande** [comment]
next lesson can you teach me how to merge?
please take a look to the new branch https://jessicadelgado.netlify.app/

**Comment by gorazd** [comment]
Sure. If you have time have a look here:
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request

**Comment by Jesande** [comment]
I think I made a mistake when I merged the branches :( ... I'm fixing the files now.

**Comment by gorazd** [comment]
I like the new layout and personal branding ✨
