### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by Jesande** [Jesande/jesande.github.io#8]
Magis layout is too messy, https://jesande.github.io/projects/magis.html
should I use grids instead of flex-box?

**Comment by gorazd** [comment]
What is bothering you?

Maybe specify the client before  the wording "configurator tool optimization".
At the end change "See this project also in" to "See this project also on".

**Comment by Jesande** [comment]
the spaces between p and img in "our solutions" section are not quite the same, it looks messy.
